//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersAssistant.Domain.Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemOrder
    {
        [Key]
        public int ItemId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        [ForeignKey("Order")]
        public int? order_id_fk { get; set; }
        public Order Order { get; set; }
        public int? numberOrdered { get; set; }
        public string product_name { get; set; }
    }
}
