//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeachersAssistant.Domain.Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SHOP_PRODS 
    {
        [Key]
        public int prodId { get; set; }
        public string prodCode { get; set; }
        public string prodName { get; set; }
        public decimal prodPrice { get; set; }
        public string prodDesc { get; set; }
        public bool IsPaidDocument { get; set; }
        public bool IsPaidVideo { get; set; }
        public int DocumentId { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> numberOfVoters { get; set; }
        public override int GetHashCode()
        {
            return (int)(prodId * 3.48) + prodName.Length + prodDesc.Length;
        }

        public override bool Equals(object obj)
        {
            return (obj as SHOP_PRODS).prodId == this.prodId;
        }
    }
}
